name: afterlight
description: "A minimalist Android launcher built with Flutter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  battery_plus: ^6.2.1
  wakelock_plus: ^1.2.11
  apps_handler: ^1.0.1
  external_app_launcher: ^4.0.3
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_svg: ^2.0.17
  gap: ^3.0.1
  gaimon: ^1.4.0
  material_symbols_icons: ^4.2811.0
  freezed_annotation: ^3.0.0
  file_picker: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  hive_ce_generator: ^1.8.2
  freezed: ^3.0.4

dependencies_override:
  freezed_annotation: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/

  fonts:
    - family: Oita
      fonts:
        - asset: assets/fonts/Oita.ttf